-- Seed categories
insert into categories (slug, name, description, icon) values
  ('workflow-automation', 'Workflow Automation', 'Consultants who design, build, and optimize automated business processes using no-code and low-code tools like Zapier, Make, and n8n.', '⚡'),
  ('ai-integration', 'AI Integration', 'Specialists who connect AI models and APIs into existing business systems, products, and internal tools.', '🤖'),
  ('data-analytics', 'Data & Analytics', 'Consultants who build automated reporting pipelines, dashboards, and data infrastructure using AI-assisted tooling.', '📊'),
  ('ai-copywriting', 'AI Copywriting & Content', 'Experts who build AI-powered content systems, prompt libraries, and automated content workflows at scale.', '✍️'),
  ('ai-strategy', 'AI Strategy & Audits', 'Advisors who assess organizational AI readiness, map automation opportunities, and build implementation roadmaps.', '🗺️');

-- Seed listings (25 across 5 categories, 8 states)
insert into listings (
  slug, business_name, category_primary, category_tags, service_delivery,
  industry_verticals, tools_expertise, price_tier, price_starting_at,
  geo_primary, geo_coverage, verified_status, claimed_status,
  availability_status, founded_year, team_size_range, certifications,
  description_short, description_long, avg_rating, review_count,
  case_study_count, response_time_avg, tier, last_verified_at
) values

-- WORKFLOW AUTOMATION (6 listings)
('apex-automation-tx', 'Apex Automation Co.', 'workflow-automation',
  ARRAY['zapier','make','crm-automation'], 'remote-only',
  ARRAY['mortgage','real-estate','fintech'], ARRAY['Zapier','Make','HubSpot','Airtable'],
  '$$', 2500, 'Austin, TX', ARRAY['Texas','Nationwide'],
  true, false, 'accepting-clients', 2021, '2-10', ARRAY['Zapier Certified Expert'],
  'Mortgage and real estate workflow automation specialists. Cut onboarding time by 60%.',
  'Apex Automation Co. builds end-to-end workflow automation for mortgage lenders, real estate brokerages, and fintech companies. Their team specializes in Zapier and Make integrations that connect CRMs, loan origination systems, and communication platforms into seamless automated pipelines. With over 40 completed implementations, they have a proven track record of reducing manual data entry by 70% and cutting client onboarding time in half.',
  4.9, 18, 8, '< 24 hours', 'pro', now()),

('clearpath-ai-ca', 'Clearpath AI', 'workflow-automation',
  ARRAY['n8n','zapier','ecommerce'], 'hybrid',
  ARRAY['ecommerce','retail','logistics'], ARRAY['n8n','Zapier','Shopify','WooCommerce'],
  '$$$', 5000, 'Los Angeles, CA', ARRAY['California','Nevada','Arizona'],
  true, false, 'accepting-clients', 2020, '2-10', ARRAY['n8n Certified'],
  'E-commerce automation specialists. Order fulfillment, inventory sync, and customer journey automation.',
  'Clearpath AI designs and deploys automation infrastructure for e-commerce brands doing $1M–$50M in annual revenue. Their core offering is a full-stack automation audit followed by a phased implementation that typically covers order management, inventory synchronization, customer communication, and returns processing. They work primarily with Shopify and WooCommerce merchants and have delivered over 60 production automation systems.',
  4.7, 24, 12, '< 4 hours', 'pro', now()),

('streamline-ops-ny', 'Streamline Ops', 'workflow-automation',
  ARRAY['make','airtable','notion'], 'remote-only',
  ARRAY['saas','startups','agencies'], ARRAY['Make','Airtable','Notion','Slack'],
  '$', 800, 'New York, NY', ARRAY['New York','New Jersey','Nationwide'],
  true, false, 'accepting-clients', 2022, 'solo', ARRAY[],
  'Solo consultant specializing in ops automation for early-stage SaaS and agencies.',
  'Streamline Ops is a solo consultancy run by a former SaaS operations manager who built and automated internal systems for two venture-backed startups before going independent. Specializes in lightweight, maintainable automation using Make, Airtable, and Notion—tools that non-technical teams can actually manage after handoff. Best fit for companies with 5–50 employees who need their first real ops infrastructure.',
  4.8, 11, 5, '< 48 hours', 'free', now()),

('autoflow-il', 'AutoFlow Systems', 'workflow-automation',
  ARRAY['zapier','salesforce','hubspot'], 'on-site',
  ARRAY['healthcare','insurance','professional-services'], ARRAY['Zapier','Salesforce','HubSpot','DocuSign'],
  '$$$', 7500, 'Chicago, IL', ARRAY['Illinois','Indiana','Wisconsin'],
  true, false, 'waitlist', 2019, '11-50', ARRAY['Salesforce Certified','HubSpot Partner'],
  'Enterprise workflow automation for healthcare and insurance. Salesforce-native implementations.',
  'AutoFlow Systems is a Chicago-based automation consultancy with a team of 15 specialists focused on regulated industries. Their healthcare and insurance clients require HIPAA-compliant automation architectures with audit trails, role-based access controls, and integration with legacy systems. AutoFlow holds Salesforce and HubSpot partner certifications and has completed implementations for three regional hospital networks and two national insurance carriers.',
  4.6, 31, 19, '< 24 hours', 'pro', now()),

('rapid-zap-tx', 'RapidZap', 'workflow-automation',
  ARRAY['zapier','gmail','google-workspace'], 'remote-only',
  ARRAY['consulting','law','accounting'], ARRAY['Zapier','Gmail','Google Workspace','Calendly'],
  '$', 500, 'Dallas, TX', ARRAY['Texas','Nationwide'],
  false, false, 'accepting-clients', 2023, 'solo', ARRAY['Zapier Certified Expert'],
  'Fast, affordable Zapier builds for professional services firms. Live in 2 weeks.',
  'RapidZap specializes in quick-turnaround Zapier implementations for law firms, accounting practices, and consulting companies. Every engagement begins with a 90-minute process audit, followed by a fixed-scope build delivered within 10 business days. Ideal for firms that need automation fast without a long discovery phase or agency retainer. Pricing is project-based with no surprise invoices.',
  4.5, 7, 4, '< 24 hours', 'free', now()),

('nexus-workflow-wa', 'Nexus Workflow', 'workflow-automation',
  ARRAY['n8n','make','api-integration'], 'hybrid',
  ARRAY['tech','saas','marketplace'], ARRAY['n8n','Make','REST APIs','Webhooks','PostgreSQL'],
  '$$', 3500, 'Seattle, WA', ARRAY['Washington','Oregon','Nationwide'],
  true, false, 'accepting-clients', 2021, '2-10', ARRAY[],
  'Technical automation consultants. API-first builds for product and engineering teams.',
  'Nexus Workflow bridges the gap between no-code automation tools and custom API development. Their team of former engineers builds automation systems that non-technical teams can operate but that are architected to handle the data volumes and reliability requirements of growing tech companies. Specializes in n8n self-hosted deployments and custom webhook infrastructure for SaaS platforms and two-sided marketplaces.',
  4.8, 14, 9, '< 24 hours', 'pro', now()),

-- AI INTEGRATION (5 listings)
('neural-bridge-ca', 'Neural Bridge', 'ai-integration',
  ARRAY['openai','claude','langchain'], 'remote-only',
  ARRAY['saas','fintech','legaltech'], ARRAY['OpenAI API','Anthropic Claude','LangChain','Python'],
  '$$$', 8000, 'San Francisco, CA', ARRAY['California','Nationwide'],
  true, false, 'accepting-clients', 2022, '2-10', ARRAY[],
  'AI API integration specialists. GPT-4 and Claude implementations for SaaS products.',
  'Neural Bridge helps SaaS companies integrate large language model capabilities into their core product. Their work includes document processing pipelines, AI-powered customer support systems, automated contract review, and natural language data query interfaces. They have delivered production AI integrations for fintech and legaltech companies with strict accuracy and compliance requirements.',
  4.9, 22, 11, '< 24 hours', 'pro', now()),

('mindful-machines-ny', 'Mindful Machines', 'ai-integration',
  ARRAY['openai','vector-db','embeddings'], 'remote-only',
  ARRAY['healthcare','research','education'], ARRAY['OpenAI API','Pinecone','Weaviate','Python','FastAPI'],
  '$$$$', 15000, 'New York, NY', ARRAY['New York','Nationwide'],
  true, false, 'waitlist', 2021, '2-10', ARRAY[],
  'RAG systems and vector database implementations for knowledge-intensive industries.',
  'Mindful Machines builds retrieval-augmented generation (RAG) systems for organizations with large, proprietary knowledge bases. Their clients include hospital systems querying clinical documentation, research institutions indexing academic literature, and universities building AI tutoring systems. Every implementation includes a custom evaluation framework to measure accuracy against domain-specific benchmarks before production deployment.',
  5.0, 9, 6, '< 48 hours', 'pro', now()),

('integrai-ga', 'IntegrAI', 'ai-integration',
  ARRAY['openai','zapier','make'], 'hybrid',
  ARRAY['ecommerce','marketing','agencies'], ARRAY['OpenAI API','Zapier','Make','Klaviyo'],
  '$$', 3000, 'Atlanta, GA', ARRAY['Georgia','Florida','Southeast'],
  true, false, 'accepting-clients', 2022, 'solo', ARRAY[],
  'AI-powered marketing automation for e-commerce and agencies. Personalization at scale.',
  'IntegrAI specializes in connecting AI language models to marketing platforms for e-commerce brands and marketing agencies. Core offerings include AI-personalized email campaigns triggered by purchase behavior, automated ad copy generation pipelines, and AI-assisted customer segmentation. The consultant previously led marketing technology at a $30M DTC brand before going independent.',
  4.6, 13, 7, '< 48 hours', 'free', now()),

('cogent-ai-tx', 'Cogent AI Solutions', 'ai-integration',
  ARRAY['azure-openai','microsoft','enterprise'], 'on-site',
  ARRAY['enterprise','manufacturing','government'], ARRAY['Azure OpenAI','Microsoft Copilot','Power Automate','SharePoint'],
  '$$$$', 20000, 'Houston, TX', ARRAY['Texas','Nationwide'],
  true, false, 'accepting-clients', 2020, '11-50', ARRAY['Microsoft Azure Certified','Power Platform Certified'],
  'Enterprise AI integration on Microsoft stack. Azure OpenAI and Copilot implementations.',
  'Cogent AI Solutions is a 20-person consultancy specializing in enterprise AI deployments on the Microsoft technology stack. Their clients are large organizations already standardized on Microsoft 365, Azure, and SharePoint who want to extend those investments with AI capabilities. Core offerings include Azure OpenAI service configuration, Microsoft Copilot customization, and Power Automate AI Builder workflows. Holds multiple Microsoft partner certifications.',
  4.7, 28, 16, '< 24 hours', 'pro', now()),

('pixelwise-ai-wa', 'Pixelwise AI', 'ai-integration',
  ARRAY['computer-vision','image-ai','product'], 'remote-only',
  ARRAY['retail','manufacturing','real-estate'], ARRAY['Google Vision API','AWS Rekognition','Python','FastAPI'],
  '$$$', 6000, 'Portland, OR', ARRAY['Oregon','Washington','California'],
  true, false, 'accepting-clients', 2022, '2-10', ARRAY[],
  'Computer vision and image AI integration for retail, manufacturing, and real estate.',
  'Pixelwise AI builds production computer vision systems integrated into business workflows. Their retail clients use image recognition for automated product cataloging and visual search. Manufacturing clients use defect detection pipelines that alert quality control teams in real time. Real estate clients use automated photo processing to flag listing images that violate platform guidelines. All implementations are delivered as containerized microservices.',
  4.8, 16, 8, '< 24 hours', 'pro', now()),

-- DATA & ANALYTICS (5 listings)
('datacraft-il', 'DataCraft Analytics', 'data-analytics',
  ARRAY['looker','dbt','bigquery'], 'hybrid',
  ARRAY['saas','fintech','retail'], ARRAY['Looker','dbt','BigQuery','Python','Airflow'],
  '$$$', 6000, 'Chicago, IL', ARRAY['Illinois','Nationwide'],
  true, false, 'accepting-clients', 2020, '2-10', ARRAY['dbt Certified','Google Cloud Certified'],
  'Modern data stack consultants. dbt, BigQuery, and Looker implementations for growth companies.',
  'DataCraft Analytics builds and maintains modern data stacks for companies that have outgrown spreadsheets but are not ready for an in-house data engineering team. Their standard engagement covers data warehouse design on BigQuery, transformation layer in dbt, and visualization in Looker or Metabase. They also build automated data quality monitoring and alerting so clients know when something breaks before their CEO does.',
  4.8, 19, 10, '< 24 hours', 'pro', now()),

('metricsmith-ca', 'MetricSmith', 'data-analytics',
  ARRAY['tableau','snowflake','python'], 'remote-only',
  ARRAY['healthcare','insurance','enterprise'], ARRAY['Tableau','Snowflake','Python','SQL','Fivetran'],
  '$$$$', 12000, 'San Diego, CA', ARRAY['California','Nationwide'],
  true, false, 'accepting-clients', 2018, '11-50', ARRAY['Tableau Partner','Snowflake Partner'],
  'Enterprise analytics and data engineering. Tableau and Snowflake for regulated industries.',
  'MetricSmith is a 35-person analytics consultancy with deep expertise in regulated industries where data governance and audit trails are non-negotiable. Their healthcare clients require HIPAA-compliant data pipelines with row-level security. Their insurance clients need actuarial reporting that ties directly to source systems. MetricSmith holds Tableau and Snowflake partnership certifications and has completed implementations for Fortune 500 companies.',
  4.7, 42, 23, '< 24 hours', 'pro', now()),

('pulse-data-tx', 'Pulse Data', 'data-analytics',
  ARRAY['google-analytics','ga4','attribution'], 'remote-only',
  ARRAY['ecommerce','marketing','dtc'], ARRAY['GA4','Google Tag Manager','Looker Studio','BigQuery'],
  '$$', 2500, 'Austin, TX', ARRAY['Texas','Nationwide'],
  true, false, 'accepting-clients', 2021, 'solo', ARRAY['Google Analytics Certified'],
  'GA4 migration, attribution modeling, and marketing analytics for DTC brands.',
  'Pulse Data specializes in marketing analytics for direct-to-consumer brands navigating the GA4 transition, iOS privacy changes, and multi-touch attribution complexity. Their standard audit covers GA4 configuration, Tag Manager cleanup, conversion tracking accuracy, and attribution model comparison. Deliverables include a clean measurement plan and a Looker Studio dashboard that marketing teams can actually use without analyst support.',
  4.9, 21, 9, '< 24 hours', 'free', now()),

('northstar-analytics-mn', 'Northstar Analytics', 'data-analytics',
  ARRAY['power-bi','azure','sql-server'], 'on-site',
  ARRAY['manufacturing','distribution','enterprise'], ARRAY['Power BI','Azure SQL','SQL Server','Power Automate'],
  '$$$', 5000, 'Minneapolis, MN', ARRAY['Minnesota','Wisconsin','Illinois','Iowa'],
  true, false, 'accepting-clients', 2019, '2-10', ARRAY['Microsoft Power BI Certified'],
  'Power BI and Azure analytics for Midwest manufacturers and distributors.',
  'Northstar Analytics serves mid-market manufacturers and distribution companies in the upper Midwest who are standardized on Microsoft infrastructure. Their team builds Power BI dashboards connected to SQL Server and Azure data sources, with automated refresh schedules and role-based access so plant managers, operations directors, and executives each see exactly the data relevant to their role. Northstar also runs quarterly Power BI training for client teams.',
  4.6, 17, 8, '< 48 hours', 'free', now()),

('signal-analytics-ny', 'Signal Analytics', 'data-analytics',
  ARRAY['mixpanel','amplitude','product-analytics'], 'remote-only',
  ARRAY['saas','mobile','consumer-tech'], ARRAY['Mixpanel','Amplitude','dbt','Segment','SQL'],
  '$$', 4000, 'New York, NY', ARRAY['New York','Nationwide'],
  true, false, 'accepting-clients', 2021, '2-10', ARRAY[],
  'Product analytics implementation for SaaS and mobile apps. Mixpanel and Amplitude specialists.',
  'Signal Analytics helps SaaS and mobile app companies build the analytics infrastructure needed to make confident product decisions. Their work covers event taxonomy design, Segment implementation, Mixpanel or Amplitude setup, funnel analysis, and retention cohort reporting. They also train product managers and designers to run their own analyses without relying on a data team for every question.',
  4.8, 15, 7, '< 24 hours', 'pro', now()),

-- AI COPYWRITING (4 listings)
('promptcraft-ca', 'PromptCraft Studio', 'ai-copywriting',
  ARRAY['content-systems','gpt4','prompt-engineering'], 'remote-only',
  ARRAY['media','publishing','agencies'], ARRAY['OpenAI GPT-4','Claude','Custom GPTs','Notion AI'],
  '$$', 3000, 'Los Angeles, CA', ARRAY['California','Nationwide'],
  true, false, 'accepting-clients', 2022, 'solo', ARRAY[],
  'AI content system design for media companies and agencies. Prompt libraries and editorial workflows.',
  'PromptCraft Studio builds AI-powered content production systems for editorial teams and marketing agencies that want to increase output without proportionally increasing headcount. Their core deliverable is a custom prompt library tuned to the client voice, paired with a workflow in Notion or Airtable that routes AI-generated drafts through human editorial review. Clients include a regional magazine group, two B2B content agencies, and a national real estate media brand.',
  4.7, 12, 6, '< 48 hours', 'free', now()),

('wordengine-tx', 'Word Engine', 'ai-copywriting',
  ARRAY['seo-content','programmatic','gpt4'], 'remote-only',
  ARRAY['ecommerce','saas','affiliate'], ARRAY['OpenAI GPT-4','Jasper','SurferSEO','Ahrefs'],
  '$$$', 5000, 'Austin, TX', ARRAY['Texas','Nationwide'],
  true, false, 'accepting-clients', 2021, '2-10', ARRAY[],
  'Programmatic SEO content systems. AI-assisted content at scale with human quality control.',
  'Word Engine builds AI-assisted content production pipelines for companies that need to publish at high volume without sacrificing quality. Their system combines AI drafting with structured human review checkpoints and SEO tooling integration. They have built content systems producing 500+ articles per month for e-commerce catalogs, SaaS knowledge bases, and affiliate sites. Every engagement includes a quality scoring rubric that editors use consistently across the team.',
  4.5, 9, 5, '< 24 hours', 'free', now()),

('voicelab-ny', 'VoiceLab AI', 'ai-copywriting',
  ARRAY['brand-voice','fine-tuning','enterprise'], 'hybrid',
  ARRAY['enterprise','consumer-brands','retail'], ARRAY['OpenAI Fine-tuning','Claude','Brand guidelines'],
  '$$$$', 18000, 'New York, NY', ARRAY['New York','Nationwide'],
  true, false, 'waitlist', 2021, '2-10', ARRAY[],
  'Brand voice AI systems for enterprise consumer brands. Fine-tuned models that write in your voice.',
  'VoiceLab AI specializes in building fine-tuned AI writing systems for large consumer brands where brand voice consistency is a legal and commercial requirement. Their process begins with a brand voice audit and corpus assembly, followed by fine-tuning and human evaluation against brand standards. Clients include a Fortune 500 CPG company, a national financial services brand, and a global hospitality chain. All models are hosted on private infrastructure.',
  4.9, 8, 4, '< 48 hours', 'pro', now()),

('contentflow-ga', 'ContentFlow', 'ai-copywriting',
  ARRAY['email-automation','klaviyo','ai-personalization'], 'remote-only',
  ARRAY['ecommerce','dtc','retail'], ARRAY['Klaviyo','OpenAI API','Make','Shopify'],
  '$$', 2800, 'Atlanta, GA', ARRAY['Georgia','Nationwide'],
  true, false, 'accepting-clients', 2023, 'solo', ARRAY[],
  'AI-personalized email sequences for Klaviyo. Dynamic content generation at the subscriber level.',
  'ContentFlow builds AI-powered email personalization systems for Klaviyo users who want to go beyond merge tags. Their system generates personalized product recommendations, subject lines, and email body variations based on individual purchase history and browsing behavior, all triggered through Klaviyo flows. Clients have seen 20–40% increases in email revenue attributed to AI-personalized sequences.',
  4.6, 10, 5, '< 24 hours', 'free', now()),

-- AI STRATEGY (4 listings)
('meridian-strategy-ca', 'Meridian AI Strategy', 'ai-strategy',
  ARRAY['ai-readiness','roadmap','executive'], 'hybrid',
  ARRAY['enterprise','healthcare','financial-services'], ARRAY['AI Auditing','Process Mapping','Change Management'],
  '$$$$', 25000, 'San Francisco, CA', ARRAY['California','Nationwide'],
  true, false, 'accepting-clients', 2019, '11-50', ARRAY[],
  'Executive AI strategy and readiness assessments for enterprises. Board-ready roadmaps.',
  'Meridian AI Strategy works with C-suite leadership at large organizations to assess AI readiness, identify high-value automation opportunities, and build phased implementation roadmaps. Their assessments cover data infrastructure maturity, organizational change readiness, regulatory risk, and competitive landscape. Deliverables are board-presentation quality and include prioritized initiative lists with ROI projections based on comparable industry implementations.',
  4.8, 14, 7, '< 24 hours', 'pro', now()),

('blueprint-ai-il', 'Blueprint AI', 'ai-strategy',
  ARRAY['smb-strategy','quick-wins','implementation'], 'remote-only',
  ARRAY['smb','professional-services','retail'], ARRAY['Process Mapping','AI Tool Selection','ROI Modeling'],
  '$$', 3500, 'Chicago, IL', ARRAY['Illinois','Nationwide'],
  true, false, 'accepting-clients', 2022, 'solo', ARRAY[],
  'Practical AI strategy for SMBs. Skip the hype, find the real opportunities in your business.',
  'Blueprint AI helps small and medium businesses identify where AI can actually save time and money in their specific operations—without the enterprise consulting price tag. Engagements begin with a 3-hour structured process interview, followed by a written audit identifying 5–10 specific automation opportunities ranked by effort and impact. The consultant then helps prioritize and implement the top 2–3 initiatives using off-the-shelf AI tools.',
  4.9, 19, 10, '< 24 hours', 'free', now()),

('vantage-point-ny', 'Vantage Point AI', 'ai-strategy',
  ARRAY['competitive-intelligence','market-analysis','ai-landscape'], 'remote-only',
  ARRAY['vc','private-equity','startups'], ARRAY['AI Due Diligence','Market Mapping','Technical Assessment'],
  '$$$', 8000, 'New York, NY', ARRAY['New York','Nationwide'],
  true, false, 'accepting-clients', 2021, '2-10', ARRAY[],
  'AI due diligence and competitive landscape analysis for investors and startups.',
  'Vantage Point AI provides AI-focused due diligence for venture capital firms evaluating AI-native investments, and competitive intelligence for startups mapping the AI tooling landscape in their category. Their technical assessments evaluate model architecture choices, data moat defensibility, and infrastructure scalability. Their competitive landscape reports are used by product teams to identify white space and by investors to assess market positioning.',
  4.7, 11, 6, '< 24 hours', 'pro', now()),

('axiom-advisory-tx', 'Axiom AI Advisory', 'ai-strategy',
  ARRAY['ai-policy','governance','compliance'], 'hybrid',
  ARRAY['enterprise','government','regulated-industries'], ARRAY['AI Governance','Policy Development','Risk Assessment'],
  '$$$$', 20000, 'Houston, TX', ARRAY['Texas','Nationwide'],
  true, false, 'accepting-clients', 2020, '2-10', ARRAY[],
  'AI governance and policy development for regulated industries and government agencies.',
  'Axiom AI Advisory helps large organizations in regulated industries build AI governance frameworks that satisfy emerging regulatory requirements while enabling responsible AI adoption. Their work covers AI use case inventory, risk classification, bias testing protocols, explainability documentation, and vendor assessment frameworks. Clients include a federal agency, two state governments, and several financial services firms navigating SEC and OCC AI guidance.',
  4.8, 12, 8, '< 48 hours', 'pro', now());
